name: musicbud_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  get_it: ^7.6.4
  connectivity_plus: ^4.0.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.1
  google_maps_flutter: ^2.5.0
  web_socket_channel: ^2.4.0
  intl: ^0.19.0
  http: ^1.1.0
  dartz: ^0.10.1
  shelf: ^1.4.1
  shelf_proxy: ^1.0.4
  url_launcher: ^6.2.5
  logging: ^1.2.0
  google_fonts: ^6.2.1
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true